python example.py --sim_per_profile 1000 --default_cost 0.1 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_2060ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.3 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_2060ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.5 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_2060ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.7 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_2060ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.9 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_2060ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.1 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_70120ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.3 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_70120ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.5 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_70120ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.7 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_70120ext_sn5b.pkl --root_result_folder experiments && \
python example.py --sim_per_profile 1000 --default_cost 0.9 --utility_type Bank_asset --is_eval False --num_rounds 10 --instance_path ./instances/networks_10banks_1000ins_70120ext_sn5b.pkl --root_result_folder experiments